import sys
import os
import datetime

# --- פונקציה לכתיבה ללוג ---
def write_log(message):
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    log_entry = f"[{timestamp}] {message}\n"
    print(log_entry.strip()) # מדפיס גם למסך
    with open("salary_calc.log", "a") as log_file:
        log_file.write(log_entry)

# --- פונקציה ליצירת דוח HTML ---
def generate_html(name, date, rate, hours, is_holiday, gross, tax, net):
    html_content = f"""
    <html>
    <head>
        <title>Salary Slip - {name}</title>
        <style>
            body {{ font-family: Arial, sans-serif; background-color: #f4f4f4; padding: 20px; }}
            .slip {{ background-color: white; padding: 20px; border-radius: 10px; width: 400px; margin: auto; box-shadow: 0 0 10px rgba(0,0,0,0.1); }}
            h1 {{ color: #333; text-align: center; }}
            .row {{ display: flex; justify-content: space-between; margin-bottom: 10px; }}
            .total {{ font-weight: bold; border-top: 2px solid #333; padding-top: 10px; margin-top: 10px; }}
            .footer {{ text-align: center; font-size: 12px; color: #777; margin-top: 20px; }}
        </style>
    </head>
    <body>
        <div class="slip">
            <h1>Salary Slip</h1>
            <div class="row"><span>Employee Name:</span> <span>{name}</span></div>
            <div class="row"><span>Date:</span> <span>{date}</span></div>
            <hr>
            <div class="row"><span>Hourly Rate:</span> <span>${rate}</span></div>
            <div class="row"><span>Hours Worked:</span> <span>{hours}</span></div>
            <div class="row"><span>Holiday Bonus:</span> <span>{'Yes (50%)' if is_holiday else 'No'}</span></div>
            <div class="row"><span>Gross Salary:</span> <span>${gross:.2f}</span></div>
            <div class="row"><span>Tax (10%):</span> <span>-${tax:.2f}</span></div>
            <div class="row total"><span>Net Salary:</span> <span>${net:.2f}</span></div>
            <div class="footer">Generated by DevOps Pipeline</div>
        </div>
    </body>
    </html>
    """
    
    with open("salary_slip.html", "w") as html_file:
        html_file.write(html_content)
    write_log(f"HTML report generated successfully for {name}.")

# --- הפונקציה הראשית ---
def main():
    # מחיקת לוג ישן אם קיים (כדי להתחיל נקי)
    if os.path.exists("salary_calc.log"):
        os.remove("salary_calc.log")

    write_log("--- Starting Salary Calculation Script ---")

    # קבלת פרמטרים מהמשתמש (דרך שורת הפקודה)
    try:
        # סדר הפרמטרים: script_name, name, rate, hours, is_holiday, date
        if len(sys.argv) < 6:
            raise ValueError("Missing arguments! Usage: python salary_calc.py <Name> <Rate> <Hours> <IsHoliday> <Date>")

        name = sys.argv[1]
        rate = float(sys.argv[2])
        hours = float(sys.argv[3])
        is_holiday_str = sys.argv[4].lower()
        date = sys.argv[5]

        # המרת בוליאני (true/false)
        is_holiday = is_holiday_str == 'true'

        write_log(f"Inputs received: Name={name}, Rate={rate}, Hours={hours}, Holiday={is_holiday}, Date={date}")

        # --- ולידציה (בדיקת תקינות) ---
        if rate < 0 or hours < 0:
            raise ValueError("Rate and Hours must be positive numbers!")

        # --- החישוב ---
        gross = rate * hours
        
        if is_holiday:
            bonus = gross * 0.5
            gross += bonus
            write_log("Holiday bonus applied (+50%).")
        
        tax = gross * 0.10 # מס של 10%
        net = gross - tax

        write_log(f"Calculation success: Gross={gross}, Net={net}")

        # --- יצירת הפלט ---
        generate_html(name, date, rate, hours, is_holiday, gross, tax, net)

    except Exception as e:
        write_log(f"ERROR: {str(e)}")
        sys.exit(1) # יציאה עם שגיאה כדי שג'נקינס ידע שנכשלנו

if __name__ == "__main__":
    main()